name: "CodeQL"

on:
  push:
    branches:
      - master
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"