name: Generate CycloneDX SBOM

on:
  push:
    branches: [master]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM for Docker Hub Image with Syft
        run: syft docker:bkimminich/juice-shop -o cyclonedx-json > juice-shop-sbom.json

      - name: Upload SBOM and Scan Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            juice-shop-sbom.json
