name: Generate CycloneDX SBOM

on:
  push:
    branches: [master]
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX Node module
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json -j

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.json
