name: Generate SBOM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate CycloneDX SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom.json

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json